version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: deploy/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - app
        labels:
            com.docker-learning.web: "Nginx Server"
        container_name: docker_nginx

    app:
        build:
            context: ./
            dockerfile: deploy/app.docker
        volumes:
            - ./:/var/www
        links:
            - database
            - cache
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
        labels:
            com.docker-learning.app: "Laravel Server"
        container_name: docker_laravel            

    database:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=homestead"
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        labels:
            com.docker-learning.db: "Database Server"
        container_name: docker_database  

    cache:
        image:  redis:latest
        ports:  
            - "6379:6379"
        labels:
            com.docker-learning.cache: "Cache Server"
        container_name: docker_cache           

volumes:
    db_data: